---
- name: Checking that both or none proxysql_cluster_name & proxysql_cluster_password are defined
  fail:
    msg: "proxysql_cluster_name & proxysql_cluster_password must be both set or false"
  when: proxysql_cluster_name != proxysql_cluster_password and (not proxysql_cluster_password or not proxysql_cluster_name)
